### ISSUE TITLE
[Bug] : Rooms labeled wrong or was not free at that time

### ISSUE THREAD

**Issue by NaiveInvestigator** [mahadihassanriyadh/chicken-coop#13]
Just as the title says. A few days ago, while hunting on a free roomi got a room which fits my time slot and also was in a floor i was never at. In the app it was labeled as a lab classroom but after reaching to my surprise it was actually the "Moot Court of Law". Well never knew it existed lol so very glad the app showed me that. But i can see some ppl getting annoyed about this.

Not related to this issue but very curious on how the app gathers the data to figure out what classrooms are used for wot. And how do they get these in the first place. Like does this app use the USIS api or something of that sort? Or is it crowdsourced? ;00

Edit: finally added the question i was forgetting about lol

**Comment by NaiveInvestigator** [comment]
ig new campus so it doesnt apply lol. Until it reappears ig

**Comment by 0xriyadh** [comment]
> ig new campus so it doesnt apply lol. Until it reappears ig

Hi @NaiveInvestigator, really sorry for not being able to get back to you before. I don't know if you are still interested to know, but to answer some of your questions:
1. We do not collect any data manually.
2. **Data collection process:** Each semester BRACU publishes a list of class schedules for that semester, you can get the latest class schedule [here (Spr24)](https://www.bracu.ac.bd/class-schedule-spring-2024). We use this pdf and with the help of some bootstrapped algorithms try to find the available classes at a given time with some very simple logic. You can find the code for these data extraction and formatting [here](https://github.com/mahadihassanriyadh/chicken-coop/tree/main/src/data/dataFormatter). 

Hope this helps. Let me know if you wanna know anything else. Love your support towards the project.

**Comment by NaiveInvestigator** [comment]
TYSMM for all the info and taking the time to reply, even more so cause it is midweek! I really really appreciate it a lot.

I actually forgot about the issue until i randomly opened it today so i dont blame u lol :> The explanations too are immensely helpful!!

> Let me know if you wanna know anything else. 

I personally think the repo should have a discussions tab for that so as to not clutter up the issues. but ig some projects again use the issues tab for discussions too. Both works lol.

**Comment by NaiveInvestigator** [comment]
vaiya totally unrelated to the topic, but since i couldn't find any place to share u this, i thought sharing it here will be better. sorry for the ping.

https://github.com/nur-zaman/better-usis

this is a project i just found yesterday. it is a complete ui overhaul of the usis. I thought maybe u guys and work together and create some cool integrations together if possible:0 or maybe contribute there ig. (i will too once i have enough coding knowledge ;-; but otherwise willing to help in any other way :> )

anyways, i sincerely thank you vaiya for your hard work. we really appreciate it a lot.

**Comment by 0xriyadh** [comment]
> I personally think the repo should have a discussions tab for that so as to not clutter up the issues. but ig some projects again use the issues tab for discussions too. Both works lol.

@NaiveInvestigator Really appreciate the feedback. However as of now we do not have any plans to expand the project further, as BRACU has moved to the new campus, and the need for this app has decreased significantly. 



> https://github.com/nur-zaman/better-usis
> 
> this is a project i just found yesterday. it is a complete ui overhaul of the usis.

Thank you for sharing this project as well, totally loved the UI and design. Currently I am a little bit busy with some other commitments, but this seems like a good project worth contributing.
