### ISSUE TITLE
[Feature Request] : Add Dark Mode toggle

### ISSUE THREAD

**Issue by NaiveInvestigator** [mahadihassanriyadh/chicken-coop#7]
Just as the title states. Sorry to bother vaiya if it was already implemented since i can't find it ;-; 

I tried looking around but no avail.

Great job on the app btw, keep it up pls! Thank you for making it Open Sourced!

Hope you consider this feature request!

**Comment by 0xriyadh** [comment]
@NaiveInvestigator Thank you for the suggestion brother. Will try soon. @Tarikul-Islam-Anik Can you please help with this issue #7?

**Comment by Tarikul-Islam-Anik** [comment]
@mahadihassanriyadh Sure!

**Comment by 0xriyadh** [comment]
Closing the issue, the issues has been addressed and resolved through PR #8.
Thank you @NaiveInvestigator for raising the issue and @Tarikul-Islam-Anik for solving it.

**Comment by NaiveInvestigator** [comment]
minor nitpick, could we also make the app header change color when switching to dark mode? 
![Screenshot_20231012-143320](https://github.com/mahadihassanriyadh/chicken-coop/assets/72654596/8a76ea93-4a4c-4dc6-a703-61a30896429d)

**Comment by Tarikul-Islam-Anik** [comment]
@NaiveInvestigator Thanks for pointing this out. I'm guessing you're using it in PWA mode. If there's any possible solution for this, then it'll be fixed by today.

**Comment by Tarikul-Islam-Anik** [comment]
@NaiveInvestigator I've tried every possible solution for fixing this.
Here's the preview link: https://chicken-coop-5c1vjhp29-mahadihassanriyadh.vercel.app/
Kindly check and let us know the results. If you still facing the issue, kindly share your browser name.

**Comment by NaiveInvestigator** [comment]
Sorry for the late reply :<< I was outside and just saw your message now.;-;

> @NaiveInvestigator Thanks for pointing this out. I'm guessing you're using it in PWA mode. If there's any possible solution for this, then it'll be fixed by today.

I think im not using the PWA, this only happens if i use the  android app linked on the readme.

But I tried using "Add to home screen" of the webapp and it looks as in the screenshot below. So i think it is the apk issue rather than the web app itself. I think just removing the header altogether will be better. if ppl need to refresh we could pull down to refresh just like any browser. 

> @NaiveInvestigator I've tried every possible solution for fixing this. Here's the preview link: https://chicken-coop-5c1vjhp29-mahadihassanriyadh.vercel.app/ Kindly check and let us know the results. If you still facing the issue, kindly share your browser name.

Sorry but I couldn't try that link in the apk version so cant tell. But I opened it on the browser as the  "Add to home screen option" and it looks the same as below. 

The apk im talking about is this btw
https://github.com/mahadihassanriyadh/chicken-coop/raw/main/Chicken-coop-app/apk%20file/chicken-coop.apk


As an aside I am willing to beta test updates on this project or any project that is related to BRACU. I can't code much so want to contribute in other ways. Just saying if u need lol. 

![Screenshot_20231012-223635](https://github.com/mahadihassanriyadh/chicken-coop/assets/72654596/c59e1bf7-a587-44f3-84e4-193f558e1cb1)

**Comment by Tarikul-Islam-Anik** [comment]
@NaiveInvestigator Thanks for your feedback. I really appreciate your enthusiasm working BRACU related projects. You can try out the PWA version. Here's how you do it:

1. Visit https://chicken-coop.vercel.app/
2. Wait for 1-2 seconds for the install button to popup.
3. Tap on the button and you're ready to go!

Since the dark mode has been implemented, I'm closing this issue. If you encounter any further issues or have additional questions, please don't hesitate to open a new issue, and we'll be happy to assist you.

We appreciate your contribution to our project and your dedication to its improvement. Your feedback is invaluable in making our project better for everyone. 

Have a great day! ⚡
